# pricing_ngin/delta_hedge.py

import numpy as np
import os
import shutil
import pandas as pd
from scipy.interpolate import interp1d
from pricing_ngin.utility_wrappers import run_full_calibration_chain, apply_spread_bump, load_interpolator
from pricing_ngin.gaussian_3_copula_pricing import GaussianCopulaPricer 
from pricing_ngin.smile import generate_interpolator

class DeltaDV01Calculator:
    
    def __init__(self, temp_base_dir='./daily_output_cache/'):
        self.temp_base_dir = temp_base_dir

    def _get_pv_prot(self, pricer: GaussianCopulaPricer, tenor, det, rho):
        """Helper to back out Protection PV (EL discounted) from pricer, mirroring 4-calibration.py."""
        # Note: price_tranche returns upfront points (0 to 1)
        t_prot = {'Attachment': 0.0, 'Detachment': det, 'Maturity': tenor, 'Spread_bps': 0, 'Type': 'Upfront'}
        upfront_prot = pricer.price_tranche(t_prot, rho)
        return upfront_prot * det

    def _price_bespoke(self, pricer: GaussianCopulaPricer, tenor, attach, detach, interpolator):
        """Calculates PV_bespoke = PV(0,D,rho_D) - PV(0,A,rho_A) using Base Correlation Mapping."""
        
        rho_attach = interpolator(attach)
        rho_detach = interpolator(detach)

        pv_prot_A = self._get_pv_prot(pricer, tenor, attach, rho_attach)
        pv_prot_D = self._get_pv_prot(pricer, tenor, detach, rho_detach)

        return pv_prot_D - pv_prot_A
    def _calculate_market_index_pv(self, tenor, data_dir, coupon_bps=100.0):
        """
        Calculates Index PV using Market Spreads + Bootstrapped Index Curve.
        PV = (Spread_Market - Coupon) * RP01
        
        Args:
            tenor (float): Maturity (e.g., 5.0)
            data_dir (str): Path containing 'CDX.NA.IG.45.csv' and 'outdata/' curves.
        """
        # 1. READ MARKET SPREAD (Bid/Ask)
        cdx_path = os.path.join(data_dir, 'CDX.NA.IG.45.csv')
        cdx_df = pd.read_csv(cdx_path)
        
        # Map float tenor (5.0) to string ('5Y')
        tenor_str = f"{int(tenor)}Y"
        row = cdx_df[cdx_df['Tenor'] == tenor_str]
        
        if row.empty:
            raise ValueError(f"No market data found for Tenor {tenor_str} in {cdx_path}")
            
        # Calculate Mid Spread
        bid = row['Bid'].values[0]
        ask = row['Ask'].values[0]
        market_spread_bps = (bid + ask) / 2.0
        
        # 2. CALCULATE RP01 (Risky Annuity)
        # Load curves generated by the pipeline in this directory
        surv_path = os.path.join(data_dir, 'outdata', 'index_survival_curve.csv')
        disc_path = os.path.join(data_dir, 'outdata', 'discount_curve.csv')
        
        if not os.path.exists(surv_path) or not os.path.exists(disc_path):
             raise FileNotFoundError(f"Missing curves in {data_dir}. Run bootstrapping first.")

        surv_df = pd.read_csv(surv_path)
        disc_df = pd.read_csv(disc_path)
        
        # Interpolators (Linear log-survival / linear log-DF or simple linear)
        # Using linear interp on factors for simplicity in integration step
        surv_func = interp1d(surv_df['Tenor'], surv_df['Survival'], kind='linear', fill_value='extrapolate')
        disc_func = interp1d(disc_df['Tenor'], disc_df['DF'], kind='linear', fill_value='extrapolate')
        
        # Integrate DF(t) * S(t) * dt
        # Quarterly steps are standard for CDS
        dt = 0.25
        time_grid = np.arange(dt, tenor + 0.001, dt)
        
        rp01 = 0.0
        for t in time_grid:
            df = float(disc_func(t))
            s = float(surv_func(t))
            rp01 += df * s * dt
            
        # 3. CALCULATE PV
        # PV = (Spread - Coupon) * RP01
        # Units: Spread in decimal (bps/10000)
        spread_dec = market_spread_bps / 10000.0
        coupon_dec = coupon_bps / 10000.0
        
        pv_index = (spread_dec - coupon_dec) * rp01
        
        return pv_index
    
    def calculate_full_dv01(self, date_str, tenor, attach, detach, raw_input_path, smile_method='ARB_FREE', bump_bps=1.0):
        """
        Calculates Tranche and Index DV01 by re-running the entire model chain for a bump.
        """
        
        bump_path = os.path.join(self.temp_base_dir, date_str, 'bump')
        base_path = os.path.join(self.temp_base_dir, date_str, 'base')
        
        # Helper to initialize pricer from existing cache
        def load_pricer_from_cache(path):
            return GaussianCopulaPricer(
                data_folder=os.path.join(path, 'outdata'), 
                discount_file='discount_curve.csv', 
                constituent_file='adjusted_constituent_survival_curves.csv'
            )

        base_marker = os.path.join(base_path, 'res', 'base_correlations.csv')

        # Check Cache
        if os.path.exists(base_marker):
            print(f"    [Base] Cache found at {base_path}. Skipping compute.")
            pricer_base = load_pricer_from_cache(base_path)
        else:
            print(f"    [Base] Computing full chain...")
            # Orchestrate Calibration Chain for Base data
            pricer_base = run_full_calibration_chain(raw_input_path, base_path)

        # --- PHASE 1: BASE RUN ---
        # pricer_base = run_full_calibration_chain(raw_input_path, base_path)
        interp_base = generate_interpolator(base_path, tenor, smile_method)
        
        base_tranche_pv = self._price_bespoke(pricer_base, tenor, attach, detach, interp_base)
        
        # base_index_pv = self._calculate_market_index_pv(tenor, raw_input_path) # Assumes existence of calculate_index_pv()
        cdx_file = 'CDX.NA.IG.45.csv'
        if not os.path.exists(os.path.join(base_path, 'CDX.NA.IG.45.csv')):
             shutil.copy2(os.path.join(raw_input_path, 'CDX.NA.IG.45.csv'), base_path)

        base_index_pv = self._calculate_market_index_pv(tenor, base_path)

        # --- PHASE 2: BUMPED RUN ---
        
        # 1. Prepare Bumped Market Data
        bump_marker = os.path.join(bump_path, 'res', 'base_correlations.csv')
        
        if os.path.exists(bump_marker):
            print(f"    [Bump] Cache found at {bump_path}. Skipping compute.")
            pricer_bumped = load_pricer_from_cache(bump_path)
        else:
            print(f"    [Bump] Computing full chain...")
            os.makedirs(bump_path, exist_ok=True)
            # Copy input files (constituents, OIS)
            for f in os.listdir(raw_input_path):
                if f != cdx_file:
                     shutil.copy2(os.path.join(raw_input_path, f), os.path.join(bump_path, f))
            
            # Create Bumped CDX
            cdx_src = os.path.join(raw_input_path, cdx_file)
            cdx_dst = os.path.join(bump_path, cdx_file)
            apply_spread_bump(cdx_src, cdx_dst, bump_bps)
            
            # Run Chain
            pricer_bumped = run_full_calibration_chain(bump_path, bump_path)
        
        #os.makedirs(bump_path, exist_ok=True)
        #for f in os.listdir(raw_input_path):
        #    if f != 'CDX.NA.IG.45.csv':
        #         shutil.copy2(os.path.join(raw_input_path, f), os.path.join(bump_path, f))
             
        # Create Bumped CDX file
        #cdx_src = os.path.join(raw_input_path, 'CDX.NA.IG.45.csv')
        #cdx_dst = os.path.join(bump_path, 'CDX.NA.IG.45.csv')
        #apply_spread_bump(cdx_src, cdx_dst, bump_bps)
        
        # 2. Orchestrate Calibration Chain for Bumped data
        #pricer_bumped = run_full_calibration_chain(bump_path, bump_path)
        interp_bumped = generate_interpolator(bump_path, tenor, smile_method)

        # 3. Price with Bumped Curves and Correlations
        bumped_tranche_pv = self._price_bespoke(pricer_bumped, tenor, attach, detach, interp_bumped)
        bumped_index_pv = self._calculate_market_index_pv(tenor, bump_path)

        # --- PHASE 3: CALCULATE DV01 ---
        
        # DV01 is the change in PV for the 1bp shift (since bump_bps=1.0)
        tranche_dv01 = (bumped_tranche_pv - base_tranche_pv)
        index_dv01 = (bumped_index_pv - base_index_pv)
        
        return {
            "tranche_dv01": tranche_dv01,
            "index_dv01": index_dv01,
            "base_tranche_pv": base_tranche_pv,
            "base_index_pv": base_index_pv
        }